var classicRules = {
    'rock > scissors': true,
    'scissors > rock': false,
    'scissors > paper': true,
    'paper > scissors': false,
    'rock > paper': false,
    'paper > rock': true,
};

var difficultRules = {
    'wanda > thor': true,
    'thor > wanda': false,
    'captainMarvel > wanda': true,
    'Wanda > captainMarvel': false,
    'hulk > wanda': true,
    'wanda > hulk': false,
    'Wanda > Spiderman': true,
    'Spiderman > wanda': false,
    'captainMarvel > thor': true,
    'thor > captainMarvel': false,
    'thor > hulk': true,
    'hulk > thor': false,
    'thor > spiderman': true,
    'spiderman > thor': false,
    'hulk > captainMarvel': true,
    'captainMarvel > hulk': false,
    'spiderman > captainMarvel': true,
    'captainMarvel > spiderman': false,
    'spiderman > hulk': true,
    'hulk > spiderman': false,
};